### ISSUE TITLE
Erros

### ISSUE THREAD

**Issue by AloneUsableUser** [AloneUsableUser/Eli#2]
Bem-vindo ao ELI!
https://github.com/AloneUsableUser/Eli
Selecione uma opção:
1. Pesquisar na Wikipedia
2. A.I
3. Interface Gráfica
Opção: 1
Digite o tópico para pesquisar na Wikipedia: Jogos de tabuleiro

Resumo da Wikipedia para 'Jogos de tabuleiro':
Ace of Aces is a two-player combat picture book game designed by Alfred Leonardi and first published in 1980 by Nova Game Designs.

Bem-vindo ao ELI!
https://github.com/AloneUsableUser/Eli
Selecione uma opção:
1. Pesquisar na Wikipedia
2. A.I
3. Interface Gráfica
Opção: 2
Traceback (most recent call last):
File "/home/usableuser/Eli/ELI/main.py", line 91, in <module>
main()
File "/home/usableuser/Eli/ELI/main.py", line 73, in main
ai_model = AIModel()
^^^^^^^^^
File "/home/usableuser/Eli/ELI/gpt_model_training.py", line 6, in __init__
self.model = GPT2LMHeadModel.from_pretrained("gpt2")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/usableuser/.local/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1450, in __getattribute__
requires_backends(cls, cls._backends)
File "/home/usableuser/.local/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1438, in requires_backends
raise ImportError("".join(failed))
ImportError:
GPT2LMHeadModel requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

Bem-vindo ao ELI!
https://github.com/AloneUsableUser/Eli
Selecione uma opção:
1. Pesquisar na Wikipedia
2. A.I
3. Interface Gráfica
Opção: 3
Iniciando o servidor ELI - Interface Gráfica...
Abrindo o navegador...

$ None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
File "/home/usableuser/Eli/ELI/server.py", line 6, in <module>
ai_model = AIModel()
^^^^^^^^^
File "/home/usableuser/Eli/ELI/gpt_model_training.py", line 6, in __init__
self.model = GPT2LMHeadModel.from_pretrained("gpt2")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/usableuser/.local/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1450, in __getattribute__
requires_backends(cls, cls._backends)
File "/home/usableuser/.local/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1438, in requires_backends
raise ImportError("".join(failed))
ImportError:
GPT2LMHeadModel requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

**Comment by AloneUsableUser** [comment]
ERRO: 
Ausência do PyTorch.
